import { Beatmap } from '../../types';

export const favoriteBeatmaps: Beatmap[] = [
  {
    id: 'blue-zenith',
    title: 'Blue Zenith (Cut Ver.)',
    artist: 'xi',
    mapper: 'Sotarks',
    stars: 7.98,
    bpm: 200,
    length: '1:03',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/292301.mp3',
    difficultyName: "sanatint's Insane",
    isFavorited: true,
  },
  {
    id: 'freedom-dive',
    title: 'FREEDOM DiVE↓',
    artist: 'xi',
    mapper: 'Nakagawa-Kanon',
    stars: 8.02,
    bpm: 222,
    length: '2:23',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/39804.mp3',
    difficultyName: 'FOUR DIMENSIONS',
    isFavorited: false,
  },
  {
    id: 'shizuku',
    title: 'Shizuku',
    artist: 'Lulish',
    mapper: 'Garden',
    stars: 5.73,
    bpm: 176,
    length: '2:08',
    status: 'loved',
    coverUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/1110158.mp3',
    difficultyName: "Garden's Extra",
    isFavorited: true,
  },
  {
    id: 'colorful',
    title: 'Colorful',
    artist: 'Shiena Nishizawa',
    mapper: 'Kibbleru',
    stars: 5.51,
    bpm: 182,
    length: '1:54',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/376434.mp3',
    difficultyName: "Kibbleru's Extra",
    isFavorited: false,
  },
  {
    id: 'koigokoro',
    title: 'Koigokoro',
    artist: 'a_hisa',
    mapper: 'Seni',
    stars: 5.17,
    bpm: 158,
    length: '2:00',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1462965326201-d02e4f455804?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/167786.mp3',
    difficultyName: "Seni's Extra",
    isFavorited: false,
  },
  {
    id: 'yoiyami',
    title: 'Yoiyami Hanabi',
    artist: 'Kyounosuke Yoshida',
    mapper: 'Deramok',
    stars: 6.43,
    bpm: 190,
    length: '2:15',
    status: 'approved',
    coverUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/643997.mp3',
    difficultyName: "Deramok's Extra",
    isFavorited: false,
  },
];
