import { Beatmap, ChallengeScore, ArchiveEntry } from '../../types';

export const favoriteBeatmaps: Beatmap[] = [
  {
    id: 'blue-zenith',
    title: 'Blue Zenith (Cut Ver.)',
    artist: 'xi',
    mapper: 'Sotarks',
    stars: 7.98,
    bpm: 200,
    length: '1:03',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/292301.mp3',
    difficultyName: "sanatint's Insane",
    isFavorited: true,
  },
  {
    id: 'freedom-dive',
    title: 'FREEDOM DiVE↓',
    artist: 'xi',
    mapper: 'Nakagawa-Kanon',
    stars: 8.02,
    bpm: 222,
    length: '2:23',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/39804.mp3',
    difficultyName: 'FOUR DIMENSIONS',
    isFavorited: false,
  },
  {
    id: 'shizuku',
    title: 'Shizuku',
    artist: 'Lulish',
    mapper: 'Garden',
    stars: 5.73,
    bpm: 176,
    length: '2:08',
    status: 'loved',
    coverUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/1110158.mp3',
    difficultyName: "Garden's Extra",
    isFavorited: true,
  },
  {
    id: 'colorful',
    title: 'Colorful',
    artist: 'Shiena Nishizawa',
    mapper: 'Kibbleru',
    stars: 5.51,
    bpm: 182,
    length: '1:54',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/376434.mp3',
    difficultyName: "Kibbleru's Extra",
    isFavorited: false,
  },
  {
    id: 'koigokoro',
    title: 'Koigokoro',
    artist: 'a_hisa',
    mapper: 'Seni',
    stars: 5.17,
    bpm: 158,
    length: '2:00',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1462965326201-d02e4f455804?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/167786.mp3',
    difficultyName: "Seni's Extra",
    isFavorited: false,
  },
  {
    id: 'yoiyami',
    title: 'Yoiyami Hanabi',
    artist: 'Kyounosuke Yoshida',
    mapper: 'Deramok',
    stars: 6.43,
    bpm: 190,
    length: '2:15',
    status: 'approved',
    coverUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/643997.mp3',
    difficultyName: "Deramok's Extra",
    isFavorited: false,
  },
];

export const votingBeatmaps: Beatmap[] = [
  {
    id: 'blue-zenith',
    title: 'Blue Zenith (Cut Ver.)',
    artist: 'xi',
    mapper: 'Sotarks',
    stars: 7.98,
    bpm: 200,
    length: '1:03',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/292301.mp3',
    difficultyName: "sanatint's Insane",
    cs: 4.0,
    ar: 9.5,
    od: 9.0,
    hp: 6.0,
    previewSeconds: 60,
    voteCount: 47,
    isVoted: false,
    isFavorited: false,
    modRequirement: 'HD',
    challengeType: 'Full Combo',
    submittedByName: 'Yanis_dzx',
  },
  {
    id: 'shizuku',
    title: 'Shizuku',
    artist: 'Lulish',
    mapper: 'Garden',
    stars: 5.73,
    bpm: 176,
    length: '2:08',
    status: 'loved',
    coverUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/1110158.mp3',
    difficultyName: "Garden's Extra",
    cs: 4.0,
    ar: 9.0,
    od: 8.5,
    hp: 5.5,
    previewSeconds: 60,
    voteCount: 31,
    isVoted: false,
    isFavorited: false,
    modRequirement: 'NM',
    challengeType: 'Best Accuracy',
    submittedByName: 'Rezki',
  },
  {
    id: 'colorful',
    title: 'Colorful',
    artist: 'Shiena Nishizawa',
    mapper: 'Kibbleru',
    stars: 5.51,
    bpm: 182,
    length: '1:54',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/376434.mp3',
    difficultyName: "Kibbleru's Extra",
    cs: 4.0,
    ar: 9.0,
    od: 8.0,
    hp: 5.0,
    previewSeconds: 60,
    voteCount: 22,
    isVoted: false,
    isFavorited: false,
    modRequirement: 'HDHR',
    challengeType: 'Lowest Miss Count',
    submittedByName: 'imed_osu',
  },
  {
    id: 'freedom-dive',
    title: 'FREEDOM DiVE↓',
    artist: 'xi',
    mapper: 'Nakagawa-Kanon',
    stars: 8.02,
    bpm: 222,
    length: '2:23',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/39804.mp3',
    difficultyName: 'FOUR DIMENSIONS',
    cs: 4.0,
    ar: 9.6,
    od: 9.2,
    hp: 6.5,
    previewSeconds: 60,
    voteCount: 18,
    isVoted: false,
    isFavorited: false,
    modRequirement: 'DT',
    challengeType: 'Top #1 Score',
    submittedByName: 'Karim_DZ',
  },
  {
    id: 'koigokoro',
    title: 'Koigokoro',
    artist: 'a_hisa',
    mapper: 'Seni',
    stars: 5.17,
    bpm: 158,
    length: '2:00',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1462965326201-d02e4f455804?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/167786.mp3',
    difficultyName: "Seni's Extra",
    cs: 3.8,
    ar: 8.8,
    od: 8.0,
    hp: 5.0,
    previewSeconds: 60,
    voteCount: 11,
    isVoted: false,
    isFavorited: false,
    modRequirement: 'HR',
    challengeType: 'Best Accuracy',
    submittedByName: 'helixia_dz',
  },
];

export const challengeScores: ChallengeScore[] = [
  { rank: 1, username: 'Yanis_dzx',  score: 8_420_320, accuracy: 99.1, misses: 0,  mods: 'HD', qualified: true  },
  { rank: 2, username: 'Rezki',      score: 7_801_440, accuracy: 98.7, misses: 1,  mods: 'NM', qualified: true  },
  { rank: 3, username: 'imed_osu',   score: 6_540_200, accuracy: 97.2, misses: 3,  mods: 'NM', qualified: false },
  { rank: 4, username: 'Karim_DZ',   score: 5_920_100, accuracy: 96.8, misses: 5,  mods: 'HR', qualified: false },
  { rank: 5, username: 'helixia_dz', score: 4_201_880, accuracy: 95.3, misses: 7,  mods: 'NM', qualified: false, isMe: true },
  { rank: 6, username: 'Djamel',     score: 3_890_750, accuracy: 94.1, misses: 9,  mods: 'NM', qualified: false },
  { rank: 7, username: 'nassim_dz',  score: 2_740_340, accuracy: 92.8, misses: 12, mods: 'EZ', qualified: false },
];

export const archiveData: ArchiveEntry[] = [
  {
    round: 3,
    month: 'July',
    year: 2026,
    participants: 61,
    winner: {
      title: 'Harumachi Clover (Swing Arrangement)',
      artist: 'HoneyComeBear',
      mapper: 'Reform',
      stars: 6.31,
      bpm: 190,
      length: '1:58',
      status: 'ranked',
      difficultyName: "Reform's Extra",
      coverUrl: 'https://images.unsplash.com/photo-1533158388-350937523dcf?w=800&h=400&fit=crop&auto=format',
      previewUrl: 'https://b.ppy.sh/preview/739697.mp3',
      mod: 'NM',
      challengeType: 'Full Combo',
      submittedBy: 'Yanis_dzx',
      votes: 52,
      totalVotes: 138,
    },
    challengeWinner: {
      username: 'Rezki',
      score: 9_102_440,
      accuracy: 99.8,
      misses: 0,
      mods: 'NM',
    },
    leaderboard: [
      { rank: 1, username: 'Rezki',      score: 9_102_440, accuracy: 99.8, misses: 0,  mods: 'NM', qualified: true  },
      { rank: 2, username: 'Yanis_dzx',  score: 8_740_120, accuracy: 99.2, misses: 0,  mods: 'HD', qualified: true  },
      { rank: 3, username: 'Azzedd',     score: 7_904_330, accuracy: 98.5, misses: 0,  mods: 'NM', qualified: true  },
      { rank: 4, username: 'imed_osu',   score: 6_210_800, accuracy: 97.1, misses: 2,  mods: 'NM', qualified: false },
      { rank: 5, username: 'helixia_dz', score: 5_440_220, accuracy: 96.3, misses: 3,  mods: 'NM', qualified: false },
      { rank: 6, username: 'Karim_DZ',   score: 4_980_110, accuracy: 95.7, misses: 5,  mods: 'HR', qualified: false },
      { rank: 7, username: 'nassim_dz',  score: 3_210_550, accuracy: 93.2, misses: 8,  mods: 'EZ', qualified: false },
    ],
  },
  {
    round: 2,
    month: 'June',
    year: 2026,
    participants: 48,
    winner: {
      title: 'Ghost Rule',
      artist: 'DECO*27',
      mapper: 'Flower',
      stars: 5.85,
      bpm: 170,
      length: '1:51',
      status: 'ranked',
      difficultyName: "Flower's Extra",
      coverUrl: 'https://images.unsplash.com/photo-1629904888780-8de0c816c333?w=800&h=400&fit=crop&auto=format',
      previewUrl: 'https://b.ppy.sh/preview/413117.mp3',
      mod: 'HD',
      challengeType: 'Best Accuracy',
      submittedBy: 'Karim_DZ',
      votes: 39,
      totalVotes: 112,
    },
    challengeWinner: {
      username: 'Yanis_dzx',
      score: 8_880_910,
      accuracy: 99.6,
      misses: 0,
      mods: 'HD',
    },
    leaderboard: [
      { rank: 1, username: 'Yanis_dzx',  score: 8_880_910, accuracy: 99.6, misses: 0,  mods: 'HD', qualified: true  },
      { rank: 2, username: 'Azzedd',     score: 8_321_000, accuracy: 99.1, misses: 0,  mods: 'HD', qualified: true  },
      { rank: 3, username: 'Rezki',      score: 7_100_200, accuracy: 98.0, misses: 1,  mods: 'NM', qualified: false },
      { rank: 4, username: 'nassim_dz',  score: 5_980_440, accuracy: 96.4, misses: 4,  mods: 'NM', qualified: false },
      { rank: 5, username: 'helixia_dz', score: 4_870_330, accuracy: 95.8, misses: 6,  mods: 'NM', qualified: false },
      { rank: 6, username: 'imed_osu',   score: 3_440_200, accuracy: 94.2, misses: 9,  mods: 'EZ', qualified: false },
    ],
  },
  {
    round: 1,
    month: 'May',
    year: 2026,
    participants: 34,
    winner: {
      title: 'Yoiyami Hanabi',
      artist: 'Kyounosuke Yoshida',
      mapper: 'Deramok',
      stars: 6.43,
      bpm: 190,
      length: '2:15',
      status: 'approved',
      difficultyName: "Deramok's Extra",
      coverUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&h=400&fit=crop&auto=format',
      previewUrl: 'https://b.ppy.sh/preview/643997.mp3',
      mod: 'HDHR',
      challengeType: 'Top #1 Score',
      submittedBy: 'nassim_dz',
      votes: 21,
      totalVotes: 74,
    },
    challengeWinner: {
      username: 'Azzedd',
      score: 7_204_880,
      accuracy: 98.3,
      misses: 0,
      mods: 'HDHR',
    },
    leaderboard: [
      { rank: 1, username: 'Azzedd',     score: 7_204_880, accuracy: 98.3, misses: 0,  mods: 'HDHR', qualified: true  },
      { rank: 2, username: 'Yanis_dzx',  score: 6_890_120, accuracy: 97.9, misses: 1,  mods: 'HD',   qualified: false },
      { rank: 3, username: 'Rezki',      score: 5_310_440, accuracy: 96.8, misses: 3,  mods: 'NM',   qualified: false },
      { rank: 4, username: 'helixia_dz', score: 4_100_220, accuracy: 95.1, misses: 5,  mods: 'NM',   qualified: false },
      { rank: 5, username: 'Karim_DZ',   score: 3_220_110, accuracy: 93.7, misses: 8,  mods: 'EZ',   qualified: false },
    ],
  },
];

export const searchBeatmaps: Beatmap[] = [
  ...favoriteBeatmaps,
  {
    id: 'ghost-rule',
    title: 'Ghost Rule',
    artist: 'DECO*27',
    mapper: 'Flower',
    stars: 5.85,
    bpm: 170,
    length: '1:51',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1629904888780-8de0c816c333?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/413117.mp3',
    difficultyName: "Flower's Extra",
  },
  {
    id: 'remote-control',
    title: 'Remote Control (Speed Up Ver.)',
    artist: 'Yunomi feat.TORIENA',
    mapper: 'mrn',
    stars: 6.02,
    bpm: 210,
    length: '1:47',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1614680376739-414d95ff43df?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/486720.mp3',
    difficultyName: "mrn's Extra",
  },
  {
    id: 'harumachi',
    title: 'Harumachi Clover (Swing Arrangement)',
    artist: 'HoneyComeBear',
    mapper: 'Reform',
    stars: 6.31,
    bpm: 190,
    length: '1:58',
    status: 'ranked',
    coverUrl: 'https://images.unsplash.com/photo-1533158388-350937523dcf?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/739697.mp3',
    difficultyName: "Reform's Extra",
  },
  {
    id: 'daidai',
    title: 'daidai',
    artist: 'Tobi Lou',
    mapper: 'Naotoshi',
    stars: 5.44,
    bpm: 157,
    length: '2:20',
    status: 'loved',
    coverUrl: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=400&h=200&fit=crop&auto=format',
    previewUrl: 'https://b.ppy.sh/preview/955957.mp3',
    difficultyName: "Naotoshi's Extra",
  },
];
